/* Agent self-service portal — functional layer.
 * Prototype note: localStorage/frontend permissions are not production security.
 */
(function(){
  function init(){
    if(typeof DB==="undefined" || typeof SESSION==="undefined") return;
    DB.agentRequests=Array.isArray(DB.agentRequests)?DB.agentRequests:[];
    DB.agentTasks=Array.isArray(DB.agentTasks)?DB.agentTasks:[];
    DB.agentNotifications=Array.isArray(DB.agentNotifications)?DB.agentNotifications:[];
    function A(){return typeof currentAgent==="function"?currentAgent():DB.agents.find(function(x){return x.id===SESSION.asAgentId;});}
    function now(){return typeof nowStamp==="function"?nowStamp():new Date().toLocaleString("fr-FR");}
    function id(p){return p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7);}
    function date(v){if(!v)return "—";var d=new Date(v);return isNaN(d)?"—":d.toLocaleDateString("fr-FR");}
    function requests(){return DB.agentRequests.filter(function(x){return x.agentId===SESSION.asAgentId;}).sort(function(a,b){return String(b.createdAt).localeCompare(String(a.createdAt));});}
    function status(s){var x=String(s||"En attente").toLowerCase();if(x.includes("refus")||x.includes("annul"))return badge("Refusée");if(x.includes("valid")||x.includes("termin")||x.includes("accept"))return badge("Validée");return badge(s||"En attente");}
    function notify(title,text){DB.agentNotifications.unshift({id:id("n"),agentId:SESSION.asAgentId,title:title,text:text,date:now(),read:false});}
    function modal(title,body,actions){
      var root=document.getElementById("modalRoot");
      root.innerHTML='<div class="overlay" id="apOverlay"><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h3>'+esc(title)+'</h3><div class="spacer"></div><button class="close-x" id="apClose">'+svg(I.x)+'</button></div><div class="modal-body">'+body+'</div><div class="modal-foot">'+actions+'</div></div></div>';
      var close=function(){root.innerHTML="";};
      document.getElementById("apClose").onclick=close;
      document.getElementById("apOverlay").onclick=function(e){if(e.target.id==="apOverlay")close();};
      return close;
    }
    window.openAgentRequestForm=function(type){
      var labels={absence:"Demande d'absence",formation:"Demande de formation",document:"Demande de document RH",profil:"Modification de mes informations",teletravail:"Demande de télétravail",social:"Demande d'action sociale",autre:"Autre demande RH"};
      var title=labels[type]||"Nouvelle demande RH";
      var extra=type==="absence"?'<div class="field"><label>Date de début</label><input type="date" id="apStart"></div><div class="field"><label>Date de fin</label><input type="date" id="apEnd"></div>':"";
      var body='<div class="form-grid"><div class="field"><label>Type</label><input disabled value="'+esc(title)+'"></div><div class="field"><label>Objet <span class="req">*</span></label><input id="apSubject" placeholder="Objet de la demande"></div><div class="field full"><label>Précisions <span class="req">*</span></label><textarea id="apDetails" placeholder="Décrivez votre demande…"></textarea></div>'+extra+'<div class="field full"><span class="hint">La demande est enregistrée dans votre espace et transmise au circuit RH.</span></div></div>';
      var close=modal(title,body,'<button class="btn" id="apCancel">Annuler</button><button class="btn primary" id="apSend">'+svg(I.check,'ic')+' Envoyer</button>');
      document.getElementById("apCancel").onclick=close;
      document.getElementById("apSend").onclick=function(){
        var subject=document.getElementById("apSubject").value.trim(),details=document.getElementById("apDetails").value.trim();
        if(!subject||!details){toast("Objet et précisions sont obligatoires");return;}
        var range="",s=document.getElementById("apStart"),e=document.getElementById("apEnd");if(s&&s.value)range+="Du "+s.value;if(e&&e.value)range+=" au "+e.value;
        DB.agentRequests.unshift({id:id("req"),agentId:SESSION.asAgentId,type:type||"autre",typeLabel:title,subject:subject,details:details+(range?"\n"+range:""),status:"En attente",createdAt:now(),updatedAt:now(),history:[{status:"En attente",date:now(),actor:"Agent"}]});
        notify("Demande envoyée",subject);save();close();render();toast("Demande envoyée à la RH");
      };
    };
    window.openAgentProfileRequest=function(){openAgentRequestForm("profil");};
    window.openAgentDocumentRequest=function(){openAgentRequestForm("document");};
    window.openAgentLeaveRequest=function(){openAgentRequestForm("absence");};
    window.openAgentTrainingRequest=function(){openAgentRequestForm("formation");};

    window.openAgentTask=function(taskId){
      var t=DB.agentTasks.find(function(x){return x.id===taskId;});if(!t)return;
      var body='<div class="info-list"><div class="row"><span class="l">Tâche</span><span class="v">'+esc(t.title||t.libelle||"Tâche")+'</span></div><div class="row"><span class="l">Échéance</span><span class="v">'+esc(date(t.deadline))+'</span></div><div class="row"><span class="l">Statut</span><span class="v">'+status(t.status)+'</span></div></div><div class="field" style="margin-top:14px"><label>Réponse / commentaire</label><textarea id="apTaskComment"></textarea></div><div class="field" style="margin-top:10px"><label>Pièce jointe</label><input type="file" id="apTaskFile"><span class="hint">Prototype : seul le nom du fichier est conservé.</span></div>';
      var close=modal("Ma tâche",body,'<button class="btn" id="apTaskClose">Fermer</button><button class="btn primary" id="apTaskDone">'+svg(I.check,'ic')+' Terminer</button>');
      document.getElementById("apTaskClose").onclick=close;
      document.getElementById("apTaskDone").onclick=function(){t.status="Terminée";t.completedAt=now();t.comment=document.getElementById("apTaskComment").value.trim();var f=document.getElementById("apTaskFile");t.attachmentName=f&&f.files[0]?f.files[0].name:"";notify("Tâche terminée",t.title||"Tâche");save();close();render();toast("Tâche terminée");};
    };
    window.markAgentNotificationsRead=function(){DB.agentNotifications.filter(function(x){return x.agentId===SESSION.asAgentId;}).forEach(function(x){x.read=true;});save();render();};

    window.openAgentReviewComment=function(rid){
      var r=DB.notations.find(function(x){return x.id===rid;});if(!r)return;
      var close=modal("Mon commentaire",' <div class="field"><label>Votre commentaire</label><textarea id="apReview">'+esc(r.commentaireAgent||"")+'</textarea><span class="hint">Votre commentaire est conservé dans le circuit d’évaluation.</span></div>','<button class="btn" id="apRc">Annuler</button><button class="btn primary" id="apRs">Enregistrer</button>');
      document.getElementById("apRc").onclick=close;
      document.getElementById("apRs").onclick=function(){r.commentaireAgent=document.getElementById("apReview").value.trim();r.dateCommentaireAgent=now();notify("Commentaire enregistré","Votre commentaire d’évaluation a été enregistré.");save();close();render();toast("Commentaire enregistré");};
    };

    window.renderAgentDashboard=function(){
      var a=A(),rs=requests(),unread=DB.agentNotifications.filter(function(x){return x.agentId===SESSION.asAgentId&&!x.read;}).length;
      var tasks=DB.agentTasks.filter(function(x){return x.agentId===SESSION.asAgentId&&!/termin/i.test(String(x.status));});
      var docs=agentDocs(),pays=agentPays(),forms=agentForms(),latestPay=pays[0];
      var initials=((a&&a.prenom)||"")[0]+((a&&a.nom)||"")[0],name=esc(a&&a.prenom||"Agent");
      var fullName=esc(agentName(a&&a.id)||((a&&a.prenom)||"")+" "+((a&&a.nom)||""));
      var direction=esc(a&&a.direction||"Service Informatique"),poste=esc(a&&a.poste||a&&a.fonction||"Agent");
      var email=esc(a&&a.email||a&&a.emailPro||"—"),tel=esc(a&&a.telephone||a&&a.tel||"—");
      var solde=(a&&a.soldes)||{CP:(a&&a.solde)||0,RTT:4,CPMF:2},cp=Number(solde.CP||0),rtt=Number(solde.RTT||4),exc=Number(solde.CPMF||2);
      var pct=function(v,t){return Math.max(4,Math.min(100,Math.round((v/t)*100)));};
      var style=document.getElementById("agentDashboardVisualStyle");
      if(!style){style=document.createElement("style");style.id="agentDashboardVisualStyle";style.textContent=
'.agent-dash{--ad-blue:#1178c9;--ad-ink:#182b4d;--ad-muted:#6d7f9b;--ad-border:#e4ebf4;display:flex;flex-direction:column;gap:16px}'+
'.agent-dash *{box-sizing:border-box}.ad-hero{min-height:150px;border-radius:14px;overflow:hidden;position:relative;padding:28px 32px;display:flex;align-items:center;background:linear-gradient(105deg,#eaf5ff,#d9eefb 42%,#83bdd9);box-shadow:0 5px 18px rgba(25,79,124,.08)}'+
'.ad-hero:after{content:"";position:absolute;right:-3%;bottom:-48%;width:58%;height:160%;border-radius:50%;background:rgba(255,255,255,.42);transform:rotate(-8deg)}'+
'.ad-hero-art{position:absolute;right:0;bottom:0;width:52%;height:100%;overflow:hidden}.ad-mountain{position:absolute;right:3%;bottom:-2px;width:72%;height:76%;background:linear-gradient(150deg,transparent 0 18%,rgba(34,105,137,.42) 19% 38%,rgba(54,130,156,.55) 39% 58%,rgba(28,91,121,.6) 59%);clip-path:polygon(0 100%,22% 54%,34% 73%,50% 18%,64% 56%,77% 38%,100% 100%)}'+
'.ad-palm{position:absolute;right:7%;bottom:5px;width:7px;height:68%;background:#487d70;transform:rotate(8deg);border-radius:8px}.ad-palm:before{content:"";position:absolute;top:-8px;left:-42px;width:90px;height:55px;background:radial-gradient(ellipse at center,rgba(40,125,100,.75) 0 18%,transparent 20%)}'+
'.ad-hero-content{position:relative;z-index:2;max-width:62%;display:flex;align-items:center;gap:20px}.ad-avatar{width:86px;height:86px;border-radius:50%;background:linear-gradient(145deg,#f7dfc5,#b97955);border:5px solid rgba(255,255,255,.9);box-shadow:0 5px 18px rgba(0,0,0,.12);display:grid;place-items:center;color:white;font-weight:800;font-size:25px;flex:0 0 auto}.ad-hero h1{margin:0 0 4px;font-size:30px;line-height:1.05;color:var(--ad-ink)}.ad-hero p{margin:0;color:#526b88;font-size:17px}.ad-slogan{font-size:13px!important;font-style:italic;margin-top:6px!important}.ad-fenua{position:absolute;right:28px;bottom:15px;z-index:2;color:white;font-size:20px;font-style:italic;text-shadow:0 1px 3px rgba(0,0,0,.25)}'+
'.ad-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px}.ad-card{background:#fff;border:1px solid var(--ad-border);border-radius:14px;box-shadow:0 3px 14px rgba(25,55,95,.06);overflow:hidden}.ad-card-head{padding:16px 18px 12px;display:flex;align-items:center;gap:10px;border-bottom:1px solid #edf1f6}.ad-icon{width:32px;height:32px;border-radius:9px;background:#edf6ff;color:var(--ad-blue);display:grid;place-items:center}.ad-icon.purple{background:#f2edff;color:#7358d7}.ad-icon.teal{background:#e9f8f7;color:#148f8a}.ad-icon.green{background:#eaf8f0;color:#2f9360}.ad-card-head h3{margin:0;font-size:16px;color:var(--ad-ink)}.ad-arrow{margin-left:auto;color:#8ca0b7;font-size:21px}.ad-card-body{padding:14px 18px}.ad-profile{display:flex;gap:14px;align-items:center}.ad-profile .ad-avatar{width:66px;height:66px;font-size:18px;border-width:3px}.ad-profile h4{margin:0;color:var(--ad-ink);font-size:17px}.ad-profile p{margin:2px 0;color:var(--ad-muted);font-size:12px}.ad-contact{display:grid;gap:7px;margin-top:14px;font-size:12px;color:#49627e}.ad-contact span{display:flex;align-items:center;gap:7px}.ad-btn{border:1px solid #abd3ed;background:#fff;color:#176ca6;border-radius:8px;padding:8px 14px;font-weight:700;font-size:12px;cursor:pointer}.ad-btn.full{width:100%;margin-top:13px}.ad-balance{margin-bottom:13px}.ad-balance:last-child{margin-bottom:0}.ad-balance-top{display:flex;justify-content:space-between;align-items:center;color:#3c5270;font-size:12px;margin-bottom:7px}.ad-balance-top b{color:var(--ad-ink);font-size:12px}.ad-bar{height:9px;background:#e9eef5;border-radius:99px;overflow:hidden}.ad-bar span{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,#75c4e8,#4d9dcc)}'+
'.ad-list{display:grid;gap:8px}.ad-item{padding:9px 10px;border:1px solid #e7edf4;border-radius:9px;display:flex;align-items:center;gap:9px}.ad-item-main{min-width:0}.ad-item-title{font-size:12px;font-weight:700;color:#273d5e;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ad-item-sub{font-size:10.5px;color:#8393a8;margin-top:2px}.ad-status{margin-left:auto;font-size:10px;font-weight:700;border-radius:99px;padding:5px 8px;white-space:nowrap}.ad-status.ok{background:#e7f7ee;color:#30905e}.ad-status.wait{background:#fff3d9;color:#ad7817}.ad-status.todo{background:#fde7e7;color:#c24a4a}.ad-task{display:flex;gap:9px;align-items:flex-start;padding:10px 0;border-bottom:1px solid #edf1f6}.ad-task:last-child{border-bottom:0}.ad-check{width:17px;height:17px;border:2px solid #aab9c9;border-radius:4px;flex:0 0 auto;margin-top:1px}.ad-event{display:flex;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid #edf1f6}.ad-event:last-child{border-bottom:0}.ad-date{width:44px;height:48px;border-radius:8px;background:#edf6ff;color:#2d7ab0;text-align:center;padding-top:6px;font-weight:800}.ad-date b{display:block;font-size:16px}.ad-date small{font-size:9px}.ad-doc-row{display:flex;align-items:center;gap:10px;padding:9px 0;color:#49627e;font-size:12px}.ad-doc-row+.ad-doc-row{border-top:1px solid #edf1f6}.ad-wide{grid-column:span 2}.ad-practice ul{list-style:none;padding:0;margin:0}.ad-practice li{padding:7px 0;border-bottom:1px solid #edf1f6;color:#4b607b;font-size:12px}.ad-practice li:last-child{border-bottom:0}.ad-footer{display:flex;justify-content:flex-end;margin-top:10px}.ad-small-link{font-size:11px;color:#1977b6;font-weight:700;cursor:pointer}.ad-empty{color:#8b99aa;font-size:12px;padding:8px 0}'+
'@media(max-width:1050px){.ad-grid{grid-template-columns:1fr 1fr}.ad-wide{grid-column:span 2}.ad-hero-content{max-width:80%}.ad-fenua{display:none}}@media(max-width:700px){.ad-grid{grid-template-columns:1fr}.ad-wide{grid-column:span 1}.ad-hero{padding:20px}.ad-hero-content{max-width:100%}.ad-hero-art{opacity:.35;width:70%}.ad-hero h1{font-size:24px}.ad-hero p{font-size:14px}.ad-avatar{width:68px;height:68px;font-size:20px}}';
        document.head.appendChild(style);
      }
      var reqHtml=rs.slice(0,3).map(function(r){var ok=/valid|accept|termin/i.test(String(r.status)),wait=/cours|attente/i.test(String(r.status));return '<div class="ad-item"><div class="ad-icon purple">'+svg(I.checklist)+'</div><div class="ad-item-main"><div class="ad-item-title">'+esc(r.subject||r.typeLabel||"Demande RH")+'</div><div class="ad-item-sub">'+esc(r.typeLabel||r.type||"RH")+' · '+esc(date(r.createdAt))+'</div></div><span class="ad-status '+(ok?"ok":wait?"wait":"todo")+'">'+esc(r.status||"En attente")+'</span></div>';}).join("")||'<div class="ad-empty">Aucune demande récente.</div>';
      var taskHtml=tasks.slice(0,3).map(function(t){return '<div class="ad-task"><span class="ad-check"></span><div class="ad-item-main"><div class="ad-item-title">'+esc(t.title||t.libelle||"Tâche RH")+'</div><div class="ad-item-sub">'+esc(t.description||"À traiter dans votre espace RH")+'</div></div><span class="ad-status todo">À faire</span></div>';}).join("")||'<div class="ad-empty">Aucune tâche à réaliser.</div>';
      var formHtml=forms.slice(0,3).map(function(f){return '<div class="ad-item"><div class="ad-icon green">✓</div><div class="ad-item-main"><div class="ad-item-title">'+esc(f.intitule||f.nom||f.formation||"Formation")+'</div><div class="ad-item-sub">'+esc(f.date||f.dateDebut||"")+'</div></div></div>';}).join("")||'<div class="ad-empty">Aucune formation récente.</div>';
      return '<div class="agent-dash"><section class="ad-hero"><div class="ad-hero-content"><div class="ad-avatar">'+esc(initials.toUpperCase())+'</div><div><h1>Bonjour '+name+' !</h1><p>Bienvenue dans votre espace personnel RH</p><p class="ad-slogan">"Des équipes engagées pour un habitat meilleur"</p></div></div><div class="ad-hero-art"><div class="ad-mountain"></div><div class="ad-palm"></div></div><div class="ad-fenua">Fenua, notre engagement ✿</div></section>'+
      '<div class="ad-grid">'+
      '<section class="ad-card"><div class="ad-card-head"><span class="ad-icon">'+svg(I.agents)+'</span><h3>Mon profil</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-profile"><div class="ad-avatar">'+esc(initials.toUpperCase())+'</div><div><h4>'+fullName+'</h4><p>'+poste+'</p><p>'+direction+'</p></div></div><div class="ad-contact"><span>✉ '+email+'</span><span>☎ '+tel+'</span><span>⌖ Siège - Papeete</span></div><button class="ad-btn full" onclick="go(\'mon-profil\')">Voir mon profil complet</button></div></section>'+
      '<section class="ad-card"><div class="ad-card-head"><span class="ad-icon teal">'+svg(I.conges)+'</span><h3>Mes absences</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-balance"><div class="ad-balance-top"><span>☂ Congés annuels</span><b>'+cp+' / 25 jours</b></div><div class="ad-bar"><span style="width:'+pct(cp,25)+'%"></span></div></div><div class="ad-balance"><div class="ad-balance-top"><span>◷ RTT</span><b>'+rtt+' / 10 jours</b></div><div class="ad-bar"><span style="width:'+pct(rtt,10)+'%"></span></div></div><div class="ad-balance"><div class="ad-balance-top"><span>☆ Congés exceptionnels</span><b>'+exc+' / 5 jours</b></div><div class="ad-bar"><span style="width:'+pct(exc,5)+'%"></span></div></div><button class="ad-btn full" onclick="go(\'mes-conges\')">Faire une demande d'absence</button></div></section>'+
      '<section class="ad-card"><div class="ad-card-head"><span class="ad-icon purple">'+svg(I.checklist)+'</span><h3>Mes demandes</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-list">'+reqHtml+'</div><div class="ad-footer"><span class="ad-small-link" onclick="go(\'mes-demandes\')">Voir toutes mes demandes →</span></div></div></section>'+
      '<section class="ad-card"><div class="ad-card-head"><span class="ad-icon teal">'+svg(I.checklist)+'</span><h3>Mes tâches à réaliser <span class="ad-status todo" style="margin-left:4px">'+tasks.length+'</span></h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-list">'+taskHtml+'</div><div class="ad-footer"><span class="ad-small-link" onclick="go(\'mes-taches\')">Voir toutes mes tâches →</span></div></div></section>'+
      '<section class="ad-card"><div class="ad-card-head"><span class="ad-icon">'+svg(I.conges)+'</span><h3>Mes prochains événements</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-list"><div class="ad-event"><div class="ad-date"><b>22</b><small>SEP</small></div><div class="ad-item-main"><div class="ad-item-title">Entretien annuel</div><div class="ad-item-sub">10h00 - 11h00 · Salle RH</div></div></div><div class="ad-event"><div class="ad-date"><b>10</b><small>OCT</small></div><div class="ad-item-main"><div class="ad-item-title">Formation</div><div class="ad-item-sub">08h00 - 16h00 · Salle de formation</div></div></div><div class="ad-event"><div class="ad-date"><b>28</b><small>NOV</small></div><div class="ad-item-main"><div class="ad-item-title">Visite médicale</div><div class="ad-item-sub">13h00 · Centre médical du travail</div></div></div></div></div></section>'+
      '<section class="ad-card"><div class="ad-card-head"><span class="ad-icon green">'+svg(I.formations)+'</span><h3>Mes formations</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-list">'+formHtml+'</div><div class="ad-footer"><span class="ad-small-link" onclick="go(\'mes-formations\')">Catalogue des formations →</span></div></div></section>'+
      '<section class="ad-card ad-wide"><div class="ad-card-head"><span class="ad-icon purple">'+svg(I.eye)+'</span><h3>Mes documents</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-doc-row">▣ <span>Bulletins de paie</span></div><div class="ad-doc-row">▧ <span>Attestations (travail, salaire, etc.)</span></div><div class="ad-doc-row">▧ <span>Contrats et arrêtés</span></div><div class="ad-doc-row">▧ <span>Évaluations et entretiens</span></div><div class="ad-doc-row">▧ <span>Mes documents personnels</span></div><button class="ad-btn" onclick="go(\'mes-documents\')">Accéder à mes documents</button></div></section>'+
      '<section class="ad-card"><div class="ad-card-head"><span class="ad-icon">'+svg(I.paie)+'</span><h3>Ma rémunération</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><div class="ad-item"><div class="ad-icon">'+svg(I.paie)+'</div><div><div class="ad-item-title">Mon dernier bulletin de paie</div><div class="ad-item-sub">'+esc(latestPay&&latestPay.periode||"Dernier bulletin disponible")+'</div></div></div><div class="ad-doc-row">▤ Historique des bulletins <span class="ad-arrow">›</span></div><div class="ad-doc-row">▤ Attestations fiscales <span class="ad-arrow">›</span></div></div></section>'+
      '<section class="ad-card ad-practice"><div class="ad-card-head"><span class="ad-icon purple">'+svg(I.agents)+'</span><h3>Ma vie pratique</h3><span class="ad-arrow">›</span></div><div class="ad-card-body"><ul><li>◷ Temps de travail et horaires</li><li>▧ Règlement intérieur</li><li>♧ Action sociale (aides, prestations)</li><li>♙ Maternité / Parentalité</li><li>▣ Mutuelle / Prévoyance</li><li>☎ Contacts utiles</li></ul></div></section>'+
      '</div></div>';
    };
    window.renderAgentRequests=function(){
      var rs=requests(),body=rs.map(function(r){return '<div class="mini-row"><div class="av">'+esc((r.typeLabel||"RH").slice(0,2).toUpperCase())+'</div><div><div class="who">'+esc(r.subject)+'</div><div class="det">'+esc(r.typeLabel||r.type)+' · '+esc(date(r.createdAt))+'</div></div><div class="spacer"></div>'+status(r.status)+'</div>';}).join("");
      return '<div class="detail-head"><div><h2>Mes demandes</h2><div class="meta">Toutes vos démarches RH au même endroit</div></div><div class="spacer"></div><button class="btn primary" onclick="openAgentRequestForm()">Nouvelle demande</button></div><div class="toolbar"><button class="btn sm" onclick="openAgentLeaveRequest()">Absence</button><button class="btn sm" onclick="openAgentTrainingRequest()">Formation</button><button class="btn sm" onclick="openAgentDocumentRequest()">Attestation / document</button><button class="btn sm" onclick="openAgentRequestForm(\'teletravail\')">Télétravail</button><button class="btn sm" onclick="openAgentProfileRequest()">Modifier mes informations</button></div><div class="panel"><div class="panel-head"><h3>Historique</h3><div class="spacer"></div><span class="tag">'+rs.length+' demande(s)</span></div><div class="panel-body">'+(body||'<div class="empty">Aucune demande pour le moment.</div>')+'</div></div>';
    };
    window.renderAgentTasks=function(){
      var ts=DB.agentTasks.filter(function(x){return x.agentId===SESSION.asAgentId;});
      var body=ts.map(function(t){return '<div class="tache-row"><div style="flex:1"><div class="cell-name">'+esc(t.title||t.libelle||"Tâche")+'</div><div class="cell-sub">'+esc(t.description||"")+'</div><div class="cell-sub">Échéance : '+esc(date(t.deadline))+'</div></div>'+status(t.status)+'<button class="btn sm" onclick="openAgentTask(\''+esc(t.id)+'\')">'+(/termin/i.test(String(t.status))?"Consulter":"Traiter")+'</button></div>';}).join("");
      return '<div class="detail-head"><div><h2>Mes tâches</h2><div class="meta">Documents et actions à fournir à la RH</div></div><div class="spacer"></div></div><div class="panel"><div class="panel-body"><div class="tache-list">'+(body||'<div class="empty">Aucune tâche en attente.</div>')+'</div></div></div>';
    };
    window.renderAgentNotifications=function(){
      var ns=DB.agentNotifications.filter(function(x){return x.agentId===SESSION.asAgentId;}).sort(function(a,b){return String(b.date).localeCompare(String(a.date));});
      var body=ns.map(function(n){return '<div class="mini-row" style="'+(!n.read?'background:var(--primary-soft);':'')+'"><div class="av">'+(!n.read?"!":"✓")+'</div><div><div class="who">'+esc(n.title)+'</div><div class="det">'+esc(n.text||"")+' · '+esc(date(n.date))+'</div></div><div class="spacer"></div>'+badge(n.read?"Lue":"Non lue")+'</div>';}).join("");
      return '<div class="detail-head"><div><h2>Notifications</h2><div class="meta">'+ns.filter(function(x){return !x.read;}).length+' non lue(s)</div></div><div class="spacer"></div><button class="btn" onclick="markAgentNotificationsRead()">Tout marquer comme lu</button></div><div class="panel"><div class="panel-body">'+(body||'<div class="empty">Aucune notification.</div>')+'</div></div>';
    };
    window.renderAgentProfile=function(){
      var a=A();if(!a)return '<div class="empty">Profil introuvable.</div>';
      var c=(a.enfants||[]).length;
      return '<div class="detail-head"><div class="av">'+esc((a.prenom||"")[0]+(a.nom||"")[0])+'</div><div><h2>Mon profil</h2><div class="meta">'+esc(agentName(a.id))+' · '+esc(a.matricule||"")+'</div></div><div class="spacer"></div><button class="btn primary" onclick="openAgentProfileRequest()">'+svg(I.edit,'ic')+' Demander une modification</button></div><div class="detail-cols"><div class="panel"><div class="panel-head"><h3>Informations personnelles</h3></div><div class="panel-body"><div class="info-list"><div class="row"><span class="l">Nom</span><span class="v">'+esc(a.nom||"—")+'</span></div><div class="row"><span class="l">Prénom</span><span class="v">'+esc(a.prenom||"—")+'</span></div><div class="row"><span class="l">Date de naissance</span><span class="v">'+esc(a.dateNaissance||"—")+'</span></div><div class="row"><span class="l">Situation familiale</span><span class="v">'+esc(a.situationFamiliale||"—")+'</span></div><div class="row"><span class="l">Enfants à charge</span><span class="v">'+c+'</span></div><div class="row"><span class="l">Email</span><span class="v">'+esc(a.email||a.emailPro||"—")+'</span></div><div class="row"><span class="l">Téléphone</span><span class="v">'+esc(a.telephone||a.tel||"—")+'</span></div></div></div></div><div class="panel"><div class="panel-head"><h3>Situation professionnelle</h3></div><div class="panel-body"><div class="info-list"><div class="row"><span class="l">Direction</span><span class="v">'+esc(a.direction||"—")+'</span></div><div class="row"><span class="l">Poste</span><span class="v">'+esc(a.poste||a.fonction||"—")+'</span></div><div class="row"><span class="l">Statut</span><span class="v">'+esc(a.statut||"—")+'</span></div><div class="row"><span class="l">Grade / échelon</span><span class="v">'+esc(a.grade||"—")+' / '+esc(a.echelon||"—")+'</span></div><div class="row"><span class="l">Entrée</span><span class="v">'+esc(a.dateEntree||"—")+'</span></div><div class="row"><span class="l">Quotité</span><span class="v">'+esc(a.quotite||100)+' %</span></div></div></div></div></div>';
    };
    window.renderAgentReviews=function(){
      var rs=typeof agentReviews==="function"?agentReviews():[];
      var body=rs.map(function(r){return '<div class="panel" style="margin-bottom:12px"><div class="panel-head"><h3>'+esc(r.campagne||r.periode||"Entretien")+'</h3><div class="spacer"></div><strong>'+esc(r.note!=null?r.note+"/20":"—")+'</strong></div><div class="panel-body"><div class="cell-sub">Commentaire du responsable</div><p>'+esc(r.commentaireResponsable||r.commentaireManager||"—")+'</p><div class="cell-sub">Mon commentaire</div><p>'+esc(r.commentaireAgent||"Non renseigné")+'</p><button class="btn sm" onclick="openAgentReviewComment(\''+esc(r.id)+'\')">Ajouter / modifier</button></div></div>';}).join("");
      return '<div class="detail-head"><div><h2>Mes entretiens</h2><div class="meta">Évaluations et observations de l’agent</div></div></div>'+(body||'<div class="empty">Aucun entretien disponible.</div>');
    };
    window.renderAgentLife=function(){
      var a=A();
      return '<div class="detail-head"><div><h2>Ma vie professionnelle</h2><div class="meta">Organisation et dispositifs au sein de l’OPH</div></div></div><div class="kpi-grid"><div class="kpi"><div class="k-lbl">Quotité</div><div class="k-val">'+esc(a&&a.quotite||100)+' %</div></div><div class="kpi"><div class="k-lbl">Pause déjeuner</div><div class="k-val">30 min</div></div><div class="kpi"><div class="k-lbl">Horaires</div><div class="k-val" style="font-size:18px">07:30–15:30</div></div></div><div class="panels"><div class="panel"><div class="panel-head"><h3>Organisation</h3></div><div class="panel-body"><div class="info-list"><div class="row"><span class="l">Vendredi</span><span class="v">07:30–14:30</span></div><div class="row"><span class="l">Pause</span><span class="v">30 min</span></div><div class="row"><span class="l">Direction</span><span class="v">'+esc(a&&a.direction||"—")+'</span></div></div></div></div><div class="panel"><div class="panel-head"><h3>Mes démarches</h3></div><div class="panel-body"><div class="toolbar"><button class="btn sm" onclick="openAgentRequestForm(\'teletravail\')">Télétravail</button><button class="btn sm" onclick="openAgentRequestForm(\'social\')">Action sociale</button><button class="btn sm" onclick="openAgentDocumentRequest()">Attestation / document</button></div></div></div></div>';
    };
    window.renderAgentMaternity=function(){
      var a=A(),m=(DB.maternite||[]).find(function(x){return x.agentId===a.id;}),docs=agentDocs().filter(function(d){return /mater|parent/i.test(String(d.categorie||d.type||""));});
      return '<div class="detail-head"><div><h2>Maternité / parentalité</h2><div class="meta">Suivi administratif et pièces à fournir</div></div><div class="spacer"></div><button class="btn" onclick="openAgentDocumentRequest()">Demander un document</button></div><div class="kpi-grid"><div class="kpi"><div class="k-lbl">Dossier</div><div class="k-val">'+(m?"Ouvert":"—")+'</div></div><div class="kpi"><div class="k-lbl">Documents liés</div><div class="k-val">'+docs.length+'</div></div></div><div class="panel"><div class="panel-head"><h3>Suivi</h3></div><div class="panel-body"><p class="hint">Les tâches administratives et documents nécessaires sont suivis ici. Les données médicales ne sont pas exposées dans l’espace agent.</p></div></div>';
    };
    window.renderAgentTraining=function(){
      var fs=typeof agentForms==="function"?agentForms():[];
      var rows=fs.map(function(f){return '<tr><td class="cell-name">'+esc(f.intitule||f.nom||f.formation||"Formation")+'</td><td>'+esc(f.organisme||f.provider||"—")+'</td><td>'+esc(f.date||f.dateDebut||"—")+'</td><td>'+esc(f.duree||"—")+'</td><td>'+status(f.statut||"Terminée")+'</td><td>'+((f.evaluationChaud||f.evaluationFroid)?'<span class="tag">Évaluations</span>':"—")+'</td></tr>';}).join("");
      return '<div class="detail-head"><div><h2>Mes formations</h2><div class="meta">Historique et évaluations</div></div><div class="spacer"></div><button class="btn primary" onclick="openAgentTrainingRequest()">Demander une formation</button></div><div class="table-wrap"><table><thead><tr><th>Formation</th><th>Organisme</th><th>Date</th><th>Durée</th><th>Statut</th><th>Évaluation</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6" class="empty">Aucune formation.</td></tr>')+'</tbody></table></div>';
    };
    if(SESSION.role==="agent" && typeof render==="function") setTimeout(render,0);
  }
  if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",init); else init();
})();